# Code Challenges

1. Develop a python function from scratch that will find the determinants of any 
 matrix.

2. Develop a python function from scratch that will find both the eigenvectors and eigenvalues of any 
 matrix.

3. Test your functions from a randomly generated 
 matrix.

In [21]:
#Determinants function
from copy import deepcopy

def smaller_matrix(original_matrix, row, column):
    # the new matrix should not affect the orignal matrix
    new_matrix = deepcopy(original_matrix)
    # the indices to do the removal depend on the original matrix
    new_matrix.remove(original_matrix[row])
    for i in range(len(new_matrix)):
            new_matrix[i].remove(new_matrix[i][column])
    return new_matrix
    
def determinant(matrix):
    num_rows = len(matrix)
    for row in matrix:
        if len(row) != num_rows:
            print("Not a square matrix")
            return None
    if len(matrix) == 2:
        simple_determinant = matrix[0][0] * \
                             matrix[1][1] - \
                             matrix[1][0] * \
                             matrix[0][1] 
        return simple_determinant
    else:
        #cofactor expansion
        answer = 0
        num_columns = num_rows
        for j in range(num_columns):
            cofactor = (-1) ** (0+j) * matrix[0][j] \
                * determinant(smaller_matrix(matrix, 0, j))
            answer += cofactor
        return answer

In [15]:
import random
import numpy as np

random_matrix = np.random.randint(1, 10, size=(3, 3))

In [20]:
random_matrix = generate_random_matrix(3)
print("Random Matrix:")
print(random_matrix)

my_det = determinant(random_matrix)
print("Determinant with my function:", my_det)

numpy_det = np.linalg.det(random_matrix)
print("Determinant with numpy:", numpy_det)

Random Matrix:
[[3, 7, 3], [9, 5, 6], [2, 5, 1]]
Determinant with my function: 51
Determinant with numpy: 51.00000000000002


In [67]:
from numpy.linalg import eig
#Eigenvectors and Eigenvalues function
def eigen_decomposition(matrix, num_iterations=100):
    matrix = np.array(matrix, dtype=float)
    size = matrix.shape[0]

    # Initialize a random vector as an initial guess for each eigenvector
    eigenvectors = np.eye(size)
    eigenvalues = np.zeros(size)

    for _ in range(num_iterations):
        prev_eigenvectors = np.copy(eigenvectors)  # Store previous eigenvectors for comparison

        for i in range(size):
            # Calculate the matrix-vector product
            Av = np.dot(matrix, eigenvectors[:, i])

            # Calculate eigenvalue
            eigenvalues[i] = np.dot(Av, eigenvectors[:, i])

            # Gram-Schmidt orthogonalization
            for j in range(i):
                Av -= np.dot(eigenvectors[:, j], Av) * eigenvectors[:, j]
            eigenvalues[i] = np.dot(Av, eigenvectors[:, i])
            
            # Update eigenvector using the normalized matrix-vector product
            eigenvectors[:, i] = Av / np.linalg.norm(Av)
    return eigenvalues, eigenvectors

In [68]:
print("Random Matrix:")
print(random_matrix)

#my function eigen
my_eigenvalue, my_eigenvector = eigen_decomposition(random_matrix)
print("Eigenvalue with my function", my_eigenvalue)
print("Eigenvector with my function", my_eigenvector)

#numpy function eigen
numpy_eigenvalue, numpy_eigenvector = eig(random_matrix)
print("Eigenvalue with numpy", numpy_eigenvalue)
print("Eigenvector with numpy", numpy_eigenvector)


Random Matrix:
[[3, 7, 3], [9, 5, 6], [2, 5, 1]]
Eigenvalue with my function [14.4884951  -4.74696078 -0.74153432]
Eigenvector with my function [[ 0.55218375 -0.55097323 -0.62571687]
 [ 0.75173716  0.65358037  0.08788602]
 [ 0.36053342 -0.51890385  0.77508351]]
Eigenvalue with numpy [14.4884951  -4.74696078 -0.74153432]
Eigenvector with numpy [[-0.55218375 -0.4826572  -0.51018136]
 [-0.75173716  0.73696428 -0.09371113]
 [-0.36053342 -0.47320786  0.85494632]]
