# CODE CHALLENGES

1. Without the use of any python libraries or modules, develop a function that can perform matrix addition, given two numpy matrices.
2. Without the use of any python libraries or modules, develop a function that can multiply two numpy matrices.
3. The rule of distributivity states that given two matrices $A$ and $B$ and a scalar, $k$, then $k(A+B)=kA+kB$. Instead of writing a proof mathematically, develop two codes for $k(A+B)$ and $kA+kB$.
4. Without using a python library or modules develop a function that can extract the diagonal of a numpy matrix.
5. Without using a python library or modules develop a function that can find a trace of a numpy matrix.

In [148]:
import numpy 

#1. Matrix Addition
def MatrixAddition(matrix1, matrix2):
    if len(matrix1) != len(matrix2) or len(matrix1[0]) != len(matrix2[0]):
        raise ValueError("Matrices must have the same dimensions for addition.")

    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[0])):
            row.append(matrix1[i][j] + matrix2[i][j])
        result.append(row)

    return result

# Example usage:
matrix_a = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

matrix_b = [
    [9, 8, 7],
    [13, 5, 4],
    [3, 2, 1]
]

result_matrix = MatrixAddition(matrix_a, matrix_b)
print("Test - my matrix addition function")
for row in result_matrix:
    print(row)

print("Numpy - matrix addition")
result = np.add(matrix_a, matrix_b)
for row in result:
    print(row)

Test - my matrix addition function
[10, 10, 10]
[17, 10, 10]
[10, 10, 10]
Numpy - matrix addition
[10 10 10]
[17 10 10]
[10 10 10]


In [149]:
#2. Matrix Multiplication
def MatrixMultiplication(matrix1, matrix2):
    # Check if the matrices can be multiplied
    if len(matrix1[0]) != len(matrix2):
        raise ValueError("Number of columns in the first matrix must be equal to the number of rows in the second matrix.")

    # Initialize the result matrix with zeros
    result = [[0 for _ in range(len(matrix2[0]))] for _ in range(len(matrix1))]

    # Perform matrix multiplication
    for i in range(len(matrix1)):
        for j in range(len(matrix2[0])):
            for k in range(len(matrix2)):
                result[i][j] += matrix1[i][k] * matrix2[k][j]

    return result

# Example usage:
matrix_a = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

matrix_b = [
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
]

result_matrix = MatrixMultiplication(matrix_a, matrix_b)
print("Test - my matrix multiplication function")
for row in result_matrix:
    print(row)

result = np.dot(matrix_a, matrix_b)
print("Numpy - matrix multiplication")
for row in result:
    print(row)

Test - my matrix multiplication function
[30, 24, 18]
[84, 69, 54]
[138, 114, 90]
Numpy - matrix multiplication
[30 24 18]
[84 69 54]
[138 114  90]


In [150]:
# 3. $k(A+B)$ and $kA+kB$
def ScalarMatrixAddition(k, matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[0])):
            row.append(k * (matrix1[i][j] + matrix2[i][j]))
        result.append(row)
    return result

def ScalarMatrixMultiplication(k, matrix):
    result = []
    for i in range(len(matrix)):
        row = []
        for j in range(len(matrix[0])):
            row.append(k * matrix[i][j])
        result.append(row)
    return result

# Example usage:
k = 2
matrix_a = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

matrix_b = [
    [9, 8, 7],
    [6, 5, 4],
    [11, 2, 1]
]

# k(A+B)
result_kApluskB = ScalarMatrixAddition(k, matrix_a, matrix_b)

# kA + kB
result_kA_kB = MatrixAddition(ScalarMatrixMultiplication(k, matrix_a), ScalarMatrixMultiplication(k, matrix_b))

# Display results
print("Test")
print("k(A+B):")
for row in result_kApluskB:
    print(row)

print("\nkA + kB:")
for row in result_kA_kB:
    print(row)

Test
k(A+B):
[20, 20, 20]
[20, 20, 20]
[36, 20, 20]

kA + kB:
[20, 20, 20]
[20, 20, 20]
[36, 20, 20]


In [151]:
#4. Diagonal of a matrix
def ExtractDiagonal(matrix):
    # Check if the matrix is square
    if len(matrix) != len(matrix[0]):
        raise ValueError("Input matrix must be square for diagonal extraction.")

    diagonal = []
    for i in range(len(matrix)):
        diagonal.append(matrix[i][i])

    return diagonal

# Example usage:
matrix_a = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

result_diagonal = ExtractDiagonal(matrix_a)
print("Test - my diagonal function")
print(result_diagonal)

result = np.diag(matrix_a)
print("Numpy - diagonal ")
print(result)

Test - my diagonal function
[1, 5, 9]
Numpy - diagonal 
[1 5 9]


In [152]:
# 5. Trace of a Matrix
def MatrixTrace(matrix):
    diagonal = extract_diagonal(matrix)
    trace_sum = sum(diagonal)
    return trace_sum

# Example usage:
matrix_a = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

result_trace = MatrixTrace(matrix_a)
print("Test - my trace function")
print(result_trace)
result = np.trace(matrix_a)
print("Numpy - Trace")
print(result)

Test - my trace function
15
Numpy - Trace
15


# Problem Solving

### 1. Solve $X$ given that

$A = \begin{bmatrix}
    1 & 2\\
    3 & 4
    \end{bmatrix} ,
    B = \begin{bmatrix}
    -1 & 0\\
    1& 1
    \end{bmatrix}
    $

a. $3X = A - 2B$ \
    $3X = \begin{bmatrix}
    1 & 2\\
    3 & 4
    \end{bmatrix} 
    - 2 \begin{bmatrix}
     -1 & 0\\
    1 & 1
    \end{bmatrix} 
    $ \
     $3X = \begin{bmatrix}
    1 & 2\\
    3 & 4
    \end{bmatrix} 
    - \begin{bmatrix}
     -2 & 0\\
    2 & 2
    \end{bmatrix} 
    $ \
     $3X \cdot \frac{1}{3} = \begin{bmatrix}
    3 & 2\\
    1 & 2
    \end{bmatrix} 
    \cdot \frac{1}{3}
    $ \
     $X = \begin{bmatrix}
    1/3 & 2/3\\
    1/3 & 2/3
    \end{bmatrix} 
    $ 

In [153]:
# 1. a. Pythonic solution
A = np.array([[1, 2], [3, 4]])
B = np.array([[-1, 0], [1, 1]])

X = (A - 2 * B) / 3 
X

array([[1.        , 0.66666667],
       [0.33333333, 0.66666667]])

b. $2(A-B+2X) = 3(X-B)$ \
    $2A-2B+4X = 3X-3B$ \
    $4X-3X = -3B + 2B - 2A$ \
    $X = -B - 2A$ \
    $X = -1 \begin{bmatrix}
    -1 & 0\\
    1 & 1
    \end{bmatrix} 
    - 2 \begin{bmatrix}
     1 & 2\\
    3 & 4
    \end{bmatrix} 
    $ \
    $X = \begin{bmatrix}
    1 & 0\\
    -1 & -1
    \end{bmatrix} 
    - \begin{bmatrix}
     2 & 4\\
    6 & 8
    \end{bmatrix} 
    $ \
    $X = \begin{bmatrix}
    -1 & -4\\
    -7 & -9
    \end{bmatrix} 
    $ 

In [154]:
# 1. b. Pythonic solution
X = (-B - 2 * A)  
X

array([[-1, -4],
       [-7, -9]])

In [155]:
# Reduced Row echelon function to test manual RREF solutions
import numpy as np

def getReducedRowEchelonForm(matrix):
    # Convert the input matrix to a numpy array
    matrix = np.array(matrix, dtype=float)
    m, n = matrix.shape
    
    # Get the number of rows and columns in the matrix
    num_rows, num_cols = matrix.shape

    # Initialize the current pivot row and pivot column
    pivot_row = 0
    pivot_col = 0

    # Perform Gaussian elimination to obtain the reduced row-echelon form
    while pivot_row < num_rows and pivot_col < num_cols:
        # Find the row with the maximum value in the current pivot column
        max_row = np.argmax(np.abs(matrix[pivot_row:, pivot_col])) + pivot_row

        # Swap the current pivot row with the row containing the maximum value
        matrix[[pivot_row, max_row]] = matrix[[max_row, pivot_row]]

        # Normalize the pivot row
        pivot_element = matrix[pivot_row, pivot_col]
        if pivot_element != 0:
            matrix[pivot_row] /= pivot_element

        # Eliminate other rows in the current pivot column
        for i in range(num_rows):
            if i != pivot_row:
                matrix[i] -= matrix[i, pivot_col] * matrix[pivot_row]

        # Move to the next pivot row and column
        pivot_row += 1
        pivot_col += 1

    # Extract the solution vector
    solution_vector = matrix[:, -1]

    return matrix, solution_vector

### 2. Write B as a linear combination of the other matrices if possible
a.
$A_1 = \begin{bmatrix}
    1 & 2\\
    -1 & 1
    \end{bmatrix},
    A_2 = \begin{bmatrix}
    0 & 1\\
    2 & 1
    \end{bmatrix},
    B_2 = \begin{bmatrix}
    2 & 5\\
    0 & 3
    \end{bmatrix}
    $\
    $A_1x + A_2y = B$ \
    $\begin{bmatrix}
    1 & 2\\
    -1 & 1
    \end{bmatrix} x+ 
    \begin{bmatrix}
    0 & 1\\
    2 & 1
    \end{bmatrix} y
    = 
    \begin{bmatrix}
    2 & 5\\
    0 & 3
    \end{bmatrix}
    $\
    $\begin{bmatrix}
    x & 2x\\
    -x & x
    \end{bmatrix} + 
    \begin{bmatrix}
    0 & y\\
    2y & y
    \end{bmatrix} 
    = 
    \begin{bmatrix}
    2 & 5\\
    0 & 3
    \end{bmatrix}
    $\
    $\begin{bmatrix}
    x & 2x + y\\
    -x + 2y & x + y
    \end{bmatrix} 
    = 
    \begin{bmatrix}
    2 & 5\\
    0 & 3
    \end{bmatrix}
    $ \
    $ x= 2$ \
    $ 2x + y = 5$ \
    $-x + 2y = 0$ \
    $x + y = 3$ \
    $
    \begin{bmatrix}
    1 & 0 & 2\\
    2 & 1 & 5 \\
    -1 & 2 & 0 \\
    1 & 1 & 3
    \end{bmatrix} 
    \xrightarrow[]{{R_3 + R_1}}
    \begin{bmatrix}
    1 & 0 & 2\\
    2 & 1 & 5 \\
    0 & 2 & 2\\
    1 & 1 & 3
    \end{bmatrix} 
    \xrightarrow[]{{\frac{1}{2}R_3}}
     \begin{bmatrix}
    1 & 0 & 2\\
    2 & 1 & 5 \\
    0 & 1 & 1 \\
    1 & 1 & 3
    \end{bmatrix} 
    \xrightarrow[]{{R_2 <=>R_3}}
    \begin{bmatrix}
    1 & 0 & 2\\
    0 & 1 & 1 \\
    2 & 1 & 5 \\
    1 & 1 & 3
    \end{bmatrix} 
    \xrightarrow[]{{R_3-2R_4}}
    \begin{bmatrix}
    1 & 0 & 2\\
    0 & 1 & 1 \\
    0 & -1 & -1 \\
    1 & 1 & 3
    \end{bmatrix} 
    \xrightarrow[]{{R_4+R_3}}
    \begin{bmatrix}
    1 & 0 & 2\\
    0 & 1 & 1 \\
    0 & -1 & -1 \\
    1 & 0 & 2
    \end{bmatrix} 
    \xrightarrow[{R_3+R_2}]{{R_4-R_1}}
    \begin{bmatrix}
    1 & 0 & 2\\
    0 & 1 & 1 \\
    0 & 0 & 0 \\
    0 & 0 & 0
    \end{bmatrix} 
    $ \
    $ x= 2$\
    $ y =1$\
    Therefore, B is a linear combination of $A_1$ & $A_2$ 

In [156]:
#2. a. Pythonic solution
matrix_A = np.array([[1, 0, 2],
              [2, 1, 5],
              [-1, 2, 0],
              [1, 1, 3]])
rref, solution = getReducedRowEchelonForm(matrix_A)
print("Matrix")
print(matrix_A)
print("Reduced Row Echelon Form")
print(rref);
print("Solution Vector")
print(solution)

Matrix
[[ 1  0  2]
 [ 2  1  5]
 [-1  2  0]
 [ 1  1  3]]
Reduced Row Echelon Form
[[1. 0. 2.]
 [0. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
Solution Vector
[2. 1. 0. 0.]


b. $A_1 = \begin{bmatrix}
    1 & 0\\
    0 & 1
    \end{bmatrix},
    A_2 = \begin{bmatrix}
    0 & 1\\
    1 & 0
    \end{bmatrix},
    A_3 = \begin{bmatrix}
    1 & -1\\
    1 & 1
    \end{bmatrix},
    B_2 = \begin{bmatrix}
    2 & 5\\
    0 & 3
    \end{bmatrix}
    $\
    $A_1x + A_2y + A_3z = B$ \
    $\begin{bmatrix}
    1 & 0\\
    0 & 1
    \end{bmatrix}x + 
    \begin{bmatrix}
    0 & 1\\
    1 & 0
    \end{bmatrix}y + 
    \begin{bmatrix}
    1 & -1\\
    1 & 1
    \end{bmatrix}z
    = \begin{bmatrix}
    2& 5\\
    0 & 3
    \end{bmatrix}
    $\
    $\begin{bmatrix}
    x & 0\\
    0 & x
    \end{bmatrix} + 
    \begin{bmatrix}
    0 & y\\
    y & 0
    \end{bmatrix} + 
    \begin{bmatrix}
    z & -z\\
    z & z
    \end{bmatrix}
    = \begin{bmatrix}
    2& 5\\
    0 & 3
    \end{bmatrix}
    $\
    $ x + z= 2$ \
    $  y - z = 5$ \
    $ y + z = 0$ \
    $x + z = 3$ \
    $\begin{bmatrix}
    1 & 0 & 1 & 2\\
    0 & 1 & -1 & 5\\
    0 & 1 & 1 & 0\\
    1 & 0 & 1 & 3\\
    \end{bmatrix}
    \xrightarrow[]{{R_4 - R_1}}
    \begin{bmatrix}
    1 & 0 & 1 & 2\\
    0 & 1 & -1 & 5\\
    0 & 1 & 1 & 0\\
    0 & 0 & 0 & 1\\
    \end{bmatrix}
     \xrightarrow[]{{}}
    $
    Infinite solution \
    Therefore, B is not a linear combination of $A_1$ , $A_2$, & $A_3$

In [157]:
#2. b. Pythonic solution
A = np.array([[1, 0, 1, 2],
              [0, 1, -1, 5],
              [0, 1, 1, 0],
              [1, 0, 1, 3]])

rref, solution = getReducedRowEchelonForm(A)
print("Matrix")
print(A)
print("Reduced Row Echelon Form")
print(rref);
print("Solution Vector - Not a linear combination due to infinite solutions")
print(solution)

Matrix
[[ 1  0  1  2]
 [ 0  1 -1  5]
 [ 0  1  1  0]
 [ 1  0  1  3]]
Reduced Row Echelon Form
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Solution Vector - Not a linear combination due to infinite solutions
[0. 0. 0. 1.]


### 3. Given the ff. Find $A^{-1}$ and use this to solve for $Ax=b_1$ $Ax=b_2$ $Ax=b_3$.
$A_1 = \begin{bmatrix}
    1 & 2\\
    2 & 6
    \end{bmatrix},
    b_1 = \begin{bmatrix}
    3 \\
    5 
    \end{bmatrix},
    b_2 = \begin{bmatrix}
    -1 \\
    2 
    \end{bmatrix},
    b_3 = \begin{bmatrix}
    2 \\
    0 
    \end{bmatrix}
    $\
    $A^{-1} = \frac{1}{ad-bc} \begin{bmatrix}
    d & -b\\
    -c & a
    \end{bmatrix}$ \
     $= \frac{1}{(1)(6)-(2)(2)} \begin{bmatrix}
    6 & -2\\
    -2 & 1
    \end{bmatrix}$ \
    $ = \frac{1}{2} \begin{bmatrix}
    6 & -2\\
    -2 & 1
    \end{bmatrix}$ \
     $A^{-1} = \begin{bmatrix}
    3 & -1\\
    -1 & 1/2
    \end{bmatrix}$\
    $x = A^{-1} b$\
    $x_1 =\begin{bmatrix}
    3 & -1\\
    -1 & 1/2
    \end{bmatrix}
    \begin{bmatrix}
    3 \\
    5 
    \end{bmatrix}
    $ \
    $
    =\begin{bmatrix}
    (3)(3) + (-1)(5)\\
    (-1)(3) + (1/2)(5)
    \end{bmatrix}
    $ \
    $
    x_1 =\begin{bmatrix}
    4\\
    -1/2
    \end{bmatrix}
    $ \
    $
    x_2 =\begin{bmatrix}
    3 & -1\\
    -1 & 1/2
    \end{bmatrix}
    \begin{bmatrix}
    -1 \\
    2 
    \end{bmatrix}
    $ \
    $
    =\begin{bmatrix}
    (3)(-1) + (-1)(2)\\
    (-1)(-1) + (1/2)(2)
    \end{bmatrix}
    $ \
     $
    x_2 =\begin{bmatrix}
    -5\\
    2
    \end{bmatrix}
    $ \
     $
    x_3 =\begin{bmatrix}
    3 & -1\\
    -1 & 1/2
    \end{bmatrix}
    \begin{bmatrix}
    2 \\
    0 
    \end{bmatrix}
    $ \
    $
     =\begin{bmatrix}
    (3)(2) + (-1)(0)\\
    (-1)(2) + (1/2)(0)
    \end{bmatrix}
    $ \
     $
    x_3 =\begin{bmatrix}
    6\\
    -2
    \end{bmatrix}
    $ 

In [158]:
#3. Pythonic Solution using Ax = b

A = np.array([[1, 2], [2, 6]])
b1 = np.array([[3], [5]])
b2 = np.array([[-1], [2]])
b3 = np.array([[2], [0]])

AInv = np.linalg.inv(A)
x1 = np.matmul(AInv, b1)
x2 = np.matmul(AInv, b2)
x3 = np.matmul(AInv, b3)

print("A^(-1)\n", AInv, "\n")
print("Ax = b1\n", x1, "\n")
print("Ax = b2\n", x2, "\n")
print("Ax = b3\n", x3, "\n")

A^(-1)
 [[ 3.  -1. ]
 [-1.   0.5]] 

Ax = b1
 [[ 4. ]
 [-0.5]] 

Ax = b2
 [[-5.]
 [ 2.]] 

Ax = b3
 [[ 6.]
 [-2.]] 



### --Solve all the linear systems by Row reducing the augmented matrix
$\begin{bmatrix}
    A | & b_1 & b_2 & b_3\\
    \end{bmatrix}
    $ \
$\begin{bmatrix}
    1 & 2 | & 3 & -1 & 2\\
    2 & 6 | & 5 & 2 & 0\\
    \end{bmatrix}
    \xrightarrow[]{{R_2-2R_1}}
    \begin{bmatrix}
    1 & 2 | & 3 & -1 & 2\\
    0 & 2 | & -1 & 4 & -4\\
    \end{bmatrix}
    \xrightarrow[]{{R_1-R_2}}
     \begin{bmatrix}
    1 & 0 | & 4 & -5 & 6\\
    0 & 2 | & -1 & 4 & -4\\
    \end{bmatrix}
    \xrightarrow[]{{\frac{1}{2}R_2}}
      \begin{bmatrix}
    1 & 0 | & 4 & -5 & 6\\
    0 & 1 | & -1/2 & 2 & -2\\
    \end{bmatrix}
    $ \
    $x_1 = \begin{bmatrix}
    4 \\
    -1/2 \\
    \end{bmatrix}
    $ \
    $ x_2 = \begin{bmatrix}
    -5 \\
    2 \\
    \end{bmatrix}
    $ \
    $ x_3 = \begin{bmatrix}
    6 \\
    -2 \\
    \end{bmatrix}
    $

In [159]:
#3. Pythonic solution for row reducing the augmented matrix
# Concatenate matrices horizontally to form the augmented matrix
augmentedMatrix = np.hstack((A, b1, b2, b3))

# Assuming getReducedRowEchelonForm is the modified function that returns both RREF and solution vector
rref_matrix, solution_vector = getReducedRowEchelonForm(augmentedMatrix)

print("Augmented Matrix:")
print(augmentedMatrix)
print("\nReduced Row Echelon Form:")
print(rref_matrix)

# Extracting components
x1 = rref_matrix[:, 2]
x2 = rref_matrix[:, 3]
x3 = rref_matrix[:, 4]

print("X1:", x1)
print("X2:", x2)
print("X3:", x3)

Augmented Matrix:
[[ 1  2  3 -1  2]
 [ 2  6  5  2  0]]

Reduced Row Echelon Form:
[[ 1.   0.   4.  -5.   6. ]
 [-0.   1.  -0.5  2.  -2. ]]
X1: [ 4.  -0.5]
X2: [-5.  2.]
X3: [ 6. -2.]


### 4. In each given, determine if b is in col(A) and w is in row(A)

a. $ A = \begin{bmatrix}
    1 & 0 & -1\\
    1 & 1 & 1\\
    \end{bmatrix} ,
    b = \begin{bmatrix}
    3 \\
    2 \\
    \end{bmatrix},
    w = \begin{bmatrix}
    -1 &1 & 1\\
    \end{bmatrix}
    $\
    $\begin{bmatrix}
    A | & B
    \end{bmatrix}
    $\
    $\begin{bmatrix}
    1 & 0 & -1 & 3\\
    1 & 1 & 1 & 2\\
    \end{bmatrix}
    \xrightarrow[]{{R_2-R_1}}
    \begin{bmatrix}
    1 & 0 & -1 & 3\\
    0 & 1 & 2 & -1\\
    \end{bmatrix}
    $\
     $\begin{bmatrix}
    A |&B
    \end{bmatrix}
    $ is in row echelon form $\therefore$ b is in col(A) \
    $\begin{bmatrix}
    A \\
    w
    \end{bmatrix}
    $ \
    $\begin{bmatrix}
    1 & 0 & -1\\
    1 & 1 & 1\\
    -1 & 1 & 1\\
    \end{bmatrix}
    \xrightarrow[{R_2-R_1}]{{R_3+R_1}}
    \begin{bmatrix}
    1 & 0 & -1\\
    0 & 1 & 2\\
    0 & 1 & 0\\
    \end{bmatrix}
    \xrightarrow[]{{R_2-R_3}}
    \begin{bmatrix}
    1 & 0 & -1\\
    0 & 0 & 2\\
    0 & 1 & 0\\
    \end{bmatrix}
     \xrightarrow[]{{R_2<=>R_3}}
    \begin{bmatrix}
    1 & 0 & -1\\
    0 & 1 & 0\\
    0 & 0 & 2\\
    \end{bmatrix}
    \xrightarrow[]{{\frac{1}{2}R_3}}
    \begin{bmatrix}
    1 & 0 & -1\\
    0 & 1 & 0\\
    0 & 0 & 1\\
    \end{bmatrix}
    \xrightarrow[]{{R_1+R_3}}
    \begin{bmatrix}
    1 & 0 & 0\\
    0 & 1 & 0\\
    0 & 0 & 1\\
    \end{bmatrix}
    $\
    $\begin{bmatrix}
    A \\
    w
    \end{bmatrix}$ is in RREF form $\therefore$ w is in row(A)

In [160]:
#4. a - Pythonic solution
A = np.array([[1, 0, -1], [1, 1, 1]])
b = np.array([[3], [2]])
w = np.array([[-1, 1, 1]])

bRref, bSolution = getReducedRowEchelonForm(np.hstack((A, b)))
wRref, wSolution = getReducedRowEchelonForm(np.vstack((A, w)))

print("Ax = b RREF\n", b_rref)
print("b is in col(A)")

print("\nAx = w RREF\n", w_rref)
print("w is in row(A)")

Ax = b RREF
 [[ 1.  0. -1.  3.]
 [ 0.  1.  2. -1.]]
b is in col(A)

Ax = w RREF
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-0. -0.  1.]]
w is in row(A)


b. $ A = \begin{bmatrix}
    1 & 1 & -1\\
    1 & 3 & 0\\
    3 & -1 & -5\\
    \end{bmatrix} ,
    b = \begin{bmatrix}
    1 \\
    2 \\
    1
    \end{bmatrix},
    w = \begin{bmatrix}
    1 & -3& -3\\
    \end{bmatrix}
    $\
    $\begin{bmatrix}
    A | & B
    \end{bmatrix}
    $\
    $ \begin{bmatrix}
    1 & 1 & -1 & 1\\
    1 & 3 & 0 & 2\\
    3 & -1 & -5 & 1
    \end{bmatrix}
    \xrightarrow[{R_2-R_1}]{{R_3-3R_1}}
    \begin{bmatrix}
    1 & 1 & -1 & 1\\
    0 & 2 & 1 & 1\\
    0 & -4 & -2 & -2
    \end{bmatrix}
    \xrightarrow[{R_3+2R_2}]{{\frac{1}{2}R_2}}
    \begin{bmatrix}
    1 & 1 & -1 & 1\\
    0 & 1 & 1/2 & 1/2\\
    0 & 0 & 0 & 0
    \end{bmatrix}
     \xrightarrow[]{{R_1-R_2}}
    \begin{bmatrix}
    1 & 0 & -3/2 & 1/2\\
    0 & 1 & 1/2 & 1/2\\
    0 & 0 & 0 & 0
    \end{bmatrix}
    $\
     $\begin{bmatrix}
    A | & B
    \end{bmatrix}
    $ is in row echelon form, $\therefore$ b is in col(A)\
    $\begin{bmatrix}
    A \\
    w
    \end{bmatrix}
    $ \
    $
    \begin{bmatrix}
    1 & 1 & -1\\
    1 & 3 & 0\\
    3 & -1 & 5\\
    1 & -3 & -3\\
    \end{bmatrix}
    \xrightarrow[{R_2-R_1}]{{R_3-3R_1 \ R_4-R_1}}
    \begin{bmatrix}
    1 & 1 & -1\\
    0 & 2 & 1\\
    0 & -4 & -2\\
    0 & -4 & -2\\
    \end{bmatrix}
    \xrightarrow[{R_3+2R_2}]{{R_4+2R_2}}
    \begin{bmatrix}
    1 & 1 & -1\\
    0 & 2 & 1\\
    0 & 0 & 0\\
    0 & 0 & 0\\
    \end{bmatrix}
    \xrightarrow[]{{\frac{1}{2}R_2}}
    \begin{bmatrix}
    1 & 1 & -1\\
    0 & 1 & 1/2\\
    0 & 0 & 0\\
    0 & 0 & 0\\
    \end{bmatrix}
      \xrightarrow[]{{R_1-R_2}}
    \begin{bmatrix}
    1 & 0 & -3/2\\
    0 & 1 & 1/2\\
    0 & 0 & 0\\
    0 & 0 & 0\\
    \end{bmatrix}
    $ \
    $\begin{bmatrix}
    A \\
    w
    \end{bmatrix}$ is in row echelon form, $\therefore$ w is in row(A)

In [161]:
#4. b - Pythonic solution
A = np.array([[1, 1, -1], [1, 3, 0], [3, -1, -5]])
b = np.array([[1], [2], [1]])
w = np.array([[1, -3, -3]])

bRref, bSolution = getReducedRowEchelonForm(np.hstack((A, b)))
wRref, wSolution = getReducedRowEchelonForm(np.vstack((A, w)))

print("Ax = b RREF\n", bRref)
print("b is in col(A)")

print("\nAx = w RREF\n", wRref)
print("w is in row(A)")

Ax = b RREF
 [[1. 0. 0. 2.]
 [0. 1. 0. 0.]
 [0. 0. 1. 1.]]
b is in col(A)

Ax = w RREF
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
w is in row(A)


### 5. Find the rank and nullity of 
$\begin{bmatrix}
    2 & 4 & 0 & 0 & 1\\
    6 & 3 & 5 & 1 & 0\\
    1 & 0 & 2 & 2 & 3\\
    1 & 1 & 1 & 1 & 1\\
    \end{bmatrix}
    $\
    $\begin{bmatrix}
    2 & 4 & 0 & 0 & 1\\
    6 & 3 & 5 & 1 & 0\\
    1 & 0 & 2 & 2 & 3\\
    1 & 1 & 1 & 1 & 1\\
    \end{bmatrix}
    \xrightarrow[{R_1-2R_4}]{{R_2-6R_4 \ R_3 - R_4}}
    \begin{bmatrix}
    0 & 2 & -2 & -2 & -1\\
    0 & -3 & -1 & -5 & -6\\
    0 & -1 & 1 & 1 & 4\\
    1 & 1 & 1 & 1 & 1\\
    \end{bmatrix}
     \xrightarrow[{}]{{R_1 <=> R_4}}
    \begin{bmatrix}
    1 & 1 & 1 & 1 & 1\\
    0 & -3 & -1 & -5 & -6\\
    0 & -1 & 1 & 1 & 4\\
     0 & 2 & -2 & -2 & -1\\
    \end{bmatrix}
     \xrightarrow[{R_2-3R_3}]{{R_4+2R_3}}
      \begin{bmatrix}
    1 & 1 & 1 & 1 & 1\\
    0 & 0 & -4 & -8 & -18\\
    0 & -1 & 1 & 1 & 4\\
     0 & 0 & 0 & 0 & 7\\
    \end{bmatrix}
     \xrightarrow[{}]{{R_2<=>R_3}}
      \begin{bmatrix}
    1 & 1 & 1 & 1 & 1\\
    0 & -1 & 1 & 1 & 4\\
     0 & 0 & -4 & -8 & -18\\
     0 & 0 & 0 & 0 & 7\\
    \end{bmatrix}
    $\
    $rank(A) = 4$\
    $rank(A) + nullity(A) = n$\
    $nullity(A) = n - rank(A)$\
    $nullity(A) = 5 - 4$\
    $nullity(A) = 1$

In [162]:
# 5. Pythonic Solution
A = np.array([[2, 4, 0, 0, 1],
              [6, 3, 5, 1, 0],
              [1, 0, 2, 2, 5],
              [1, 1, 1, 1, 1]])

rank = np.linalg.matrix_rank(A)
nullity = A.shape[1] - rank

print("rank(A) =", rank)
print("nullity(A) =", nullity)

rank(A) = 4
nullity(A) = 1
