# Systems of Linear Equation Homework

# Assignment 1
To complete the process of determining the solution, create a function or steps of function that will automate backward substitution.

In [122]:
# Pythonic Solutions
# the following functions are the steps involved in forward elimination
import numpy as np

def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp
        
    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale
        
    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to 
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A
    
    B = np.copy(A).astype('float64')
        
    for j in range(n):
        B[l][j] += B[k][j]*scale
        
    return B

def BackwardSubstitution(A):
    # Perform backward substitution to find the solution to the linear system Ax = b,
    # where A is the augmented matrix of shape (n, n+1) resulting from forward elimination.
    
    # Parameters:
    # A (numpy.ndarray): Augmented matrix resulting from forward elimination.
    
    # Returns:
    # x (numpy.ndarray): The solution vector.
    
    n = A.shape[0]
    x = np.zeros(n, dtype=float)
    
    for i in range(n - 1, -1, -1):
        x[i] = A[i, -1] / A[i, i]
        
        for j in range(i - 1, -1, -1):
            A[j, -1] -= A[j, i] * x[i]
    
    return x
    

In [123]:
# Ab = np.array([[1.0, -1.0, 1.0, 3.0],
#               [0.0, 1.0, 2.0, 4.0],
#               [-0.0, -0.0, 1.0, 2.0]], dtype=float)

# Ab = np.array([[1.0, 0.0, 1.0],
#                [0.0, 1.0, 1.0]], dtype=float)
Ab = np.array([[1.0, 0.0, 0.0, 0.0],
               [0.0, 1.0, -0.20, 0.0],
               [0.0, 0.0, 1.0, 0.0]], dtype=float)


try:
    solution = BackwardSubstitution(Ab)
    print("Solution:", solution)
except ValueError as e:
    print(e)

Solution: [0. 0. 0.]


### 1. Provide the reasons why each of the ff equations is, or is not a linear equation

- $cos \theta x + 4y + z = \sqrt{14}$ - linear equation because all variables are raised to the power of 1 and all variables are multiplied by constants
- $cos x4y + z = \sqrt{3}$ - not linear because contains a trigonometric function, the presence of the product is the cosine inside the function makes it non linear
- $x^-1 + 7y + z = sin (\frac{\pi}{2})$ - not linear because x is raised to the power of -1
- $x^1 + y^1 + z^1 = 0 $ - linear equation because it is equal to $x + y + z =0 $ which follows the form of linear equations

### 2. Find the solutions of the linear equations
- $2x_1 + 3x_2 = 5 $ \
  $x_1 = \frac{5-3x_2}{2}$ \
  $ x_2 = \frac{5-2x_1}{3} $
- $4x_1 + 3x_2 + 2x_3 = 1$
  $x_1 = \frac{1 - 3x_2 - 2x_3}{4}$ \
  $x_2 = \frac{1 - 4x_1 - 2x_3}{3}$ \
  $x_3 = \frac{1 - 4x_1 - 3x_2}{2}$
- $3x - 6y = 0$ \
  $ x=2y $ \
  $ y=\frac{x}{2}$

### 3. Solve for the ff system of linear equations

a.  $x-y = 0$ \
    $2x +y = 3 $ \
    $\begin{bmatrix}
    1 & -1 & 0\\
    2 & 1 & 3
    \end{bmatrix} 
    \xrightarrow[]{{R_1 + R_2}}
    \begin{bmatrix}
    3 & 0 & 3\\
    2 & 1 & 3
    \end{bmatrix} 
    \xrightarrow[]{{\frac{R_1}{3}}}
    \begin{bmatrix}
    1 & 0 & 1\\
    2 & 1 & 3
    \end{bmatrix} 
    \xrightarrow[]{{R_2 - 2R1}}
    \begin{bmatrix}
    1 & 0 & 1\\
    0 & 1 & 1
    \end{bmatrix} $ \
    $y = 1 $ \
    $x = 1 $

In [124]:
A = np.array([[1.0, -1.0, 0.0],
               [2.0, 1.0, 3.0]], dtype=float)
A1 = RowAdd(A,1,0,1)
print("A1")
print(A1);

A2 = RowScale(A1,0,1.0/3)
print("A2")
print(A2);

A3 = RowAdd(A2,0,1,-2)
print("A3")
print(A3);

A4 = BackwardSubstitution(A3)
print("A4")
print(A4)

A1
[[3. 0. 3.]
 [2. 1. 3.]]
A2
[[1. 0. 1.]
 [2. 1. 3.]]
A3
[[1. 0. 1.]
 [0. 1. 1.]]
A4
[1. 1.]


b. $x-5y = -1$ \
    $-x +y = -5 $ \
    $2x +4y = 4 $ \
    $\begin{bmatrix}
    1 & 5 & -1 \\
    -1 & 1 & -5 \\
    2 & 4 & 4
    \end{bmatrix} 
    \xrightarrow[{R_3-2R_1}]{{R_2 + R_1}}
    \begin{bmatrix}
    1 & 5 & -1 \\
    0 & 6 & -6 \\
    0 & -6 & 6
    \end{bmatrix} 
    \xrightarrow[{\frac{R_2}{6}}]{{R_3 + R_2}}
    \begin{bmatrix}
    1 & 5 & -1 \\
    0 & 1 & -1 \\
    0 & 0 & 0
    \end{bmatrix} 
    \xrightarrow[]{{R_1 - 5R_2}} 
    \begin{bmatrix}
    1 & 0 & 4 \\
    0 & 1 & -1 \\
    0 & 0 & 0
    \end{bmatrix} 
    \xrightarrow[]{} 
    $ 
    infinite solutions

In [125]:
A = np.array([[1.0, 5.0, -1.0],
              [-1.0, 1.0, -5.0],
              [2.0, 4.0, 4.0]], dtype=float)

A1 = RowAdd(A,0,1,1)
A1 = RowAdd(A1,0,2,-2)
print("A1")
print(A1);

A2 = RowAdd(A1,1,2,1)
A2 = RowScale(A2,1,1.0/6)
print("A2")
print(A2);

A3 = RowAdd(A2,1,0,-5)
print("A3")
print(A3);

A4 = BackwardSubstitution(A3)
print("A4")
print(A4)

A1
[[ 1.  5. -1.]
 [ 0.  6. -6.]
 [ 0. -6.  6.]]
A2
[[ 1.  5. -1.]
 [ 0.  1. -1.]
 [ 0.  0.  0.]]
A3
[[ 1.  0.  4.]
 [ 0.  1. -1.]
 [ 0.  0.  0.]]
A4
[nan nan nan]


/var/folders/gz/h6s5flr16sqcrdbrjz0xxdc40000gn/T/ipykernel_87948/2680572774.py:67: RuntimeWarning: invalid value encountered in scalar divide
  x[i] = A[i, -1] / A[i, i]


c.  $2x_1 + 3x_2 - x_3 = -1$ \
    $ x_1 +x_3 = 0 $ \
    $-x_1 + 2x_2 -2x_3 = 0 $ \
     $\begin{bmatrix}
    2 & 3 & -1 & -1\\
    1 & 0 & 1 & 0\\
    -1 & 2 & -2 & 0
    \end{bmatrix} 
    \xrightarrow[]{{\frac{R_1}{2}}}
    \begin{bmatrix}
    1 & 3/2 & -1/2 & -1/2\\
    1 & 0 & 1 & 0\\
    -1 & 2 & -2 & 0
    \end{bmatrix} 
    \xrightarrow[{R_3+R_1}]{{R_2-R_1}}
    \begin{bmatrix}
    1 & 3/2 & -1/2 & -1/2\\
    0 & -3/2 & 3/2 & 1/2\\
    0 & 7/2 & -5/2 & -1/2
    \end{bmatrix} 
    \xrightarrow[]{{\frac{-2}{3}R_2}}
    \begin{bmatrix}
    1 & 3/2 & -1/2 & -1/2\\
    0 & 1 & -1 & -1/3\\
    0 & 7/2 & -5/2 & -1/2
    \end{bmatrix} 
     \xrightarrow[]{{R_3 - \frac{7}{2}R_2}}
    \begin{bmatrix}
    1 & 3/2 & -1/2 & -1/2\\
    0 & 1 & -1 & -1/3\\
    0 & 0 & 1 & 2/3
    \end{bmatrix} 
    \xrightarrow[{R_1 + \frac{1}{2}R3}]{{R_2+R_3}}
    \begin{bmatrix}
    1 & 3/2 & 0 & -1/6\\
    0 & 1 & 0 & 1/3\\
    0 & 0 & 1 & 2/3
    \end{bmatrix} 
    \xrightarrow[]{{R_1 - \frac{3}{2}R_2}}
    \begin{bmatrix}
    1 & 0 & 0 & -2/3\\
    0 & 1 & 0 & 1/3\\
    0 & 0 & 1 & 2/3
    \end{bmatrix} 
    $ \
    $ x_1 = -2/3$ \
    $ x_2 = 1/3$ \
    $ x_3 = 2/3$

In [126]:
A = np.array([[2.0, 3.0, -1.0, -1.0],
              [1.0, 0.0, 1.0, 0],
              [-1.0, 2.0, -2.0, 0]], dtype=float)

A1 = RowScale(A,0,1.0/2)
print("A1")
print(A1);

A2 = RowAdd(A1,0,1,-1)
A2 = RowAdd(A2,0,2,1)
print("A2")
print(A2);

A3 = RowScale(A2,1,-2.0/3)
print("A3")
print(A3);

A4 = RowAdd(A3,1,2,-7/2)
print("A4")
print(A4);

A4 = RowAdd(A3,1,2,-7/2)
print("A4")
print(A4);

A5 = BackwardSubstitution(A4)
print("A5")
print(A5)

A1
[[ 1.   1.5 -0.5 -0.5]
 [ 1.   0.   1.   0. ]
 [-1.   2.  -2.   0. ]]
A2
[[ 1.   1.5 -0.5 -0.5]
 [ 0.  -1.5  1.5  0.5]
 [ 0.   3.5 -2.5 -0.5]]
A3
[[ 1.    1.5  -0.5  -0.5 ]
 [-0.    1.   -1.   -0.33]
 [ 0.    3.5  -2.5  -0.5 ]]
A4
[[ 1.    1.5  -0.5  -0.5 ]
 [-0.    1.   -1.   -0.33]
 [ 0.    0.    1.    0.67]]
A4
[[ 1.    1.5  -0.5  -0.5 ]
 [-0.    1.   -1.   -0.33]
 [ 0.    0.    1.    0.67]]
A5
[-0.67  0.33  0.67]


### 4. Provide reasons why the given matrices are either a row echelon, a reduced row echelon, or neither both.
   a. $\begin{pmatrix}
    1 & 0 & 1 \\
    0 & 0 & 3 \\
    0 & 1 & 0
    \end{pmatrix} $ - Not row echelon, leading entry of the 2nd row is not to the left of the leading entry of the 1st row \
    b. $\begin{pmatrix}
    7 & 0 & 1 & 0\\
    0 & 1 & -1 & 4\\
    0 & 0 & 0 & 0
    \end{pmatrix} $ - row echelon but not reduce, since the leading entries are != 1, leading entries are in column to the left to the entry below it, and all zero row is at the bottom \
    c. $\begin{pmatrix}
    0 & 1 & 3 & 0\\
    0 & 0 & 0 & 1
    \end{pmatrix} $ - reduced row echelon, since leading entries are 1 and leading entry of the 2nd row is to the right of the leading entry of the 1st row \
    d. $\begin{pmatrix}
    0 & 0 & 0 \\
    0 & 0 & 0 \\
     0 & 0 & 0 
    \end{pmatrix} $ - reduced row echelon, all entries are zeros \
    e. $\begin{pmatrix}
    1 & 0 & 3 & -4 & 0\\
    0 & 0 & 0 & 0& 0\\
     0 & 1 & 5 & 0& 1
    \end{pmatrix} $ -  not row echelon, row with all zeros is not at the bottom\
    f. $\begin{pmatrix}
    0 & 0 & 1 \\
    0 & 1 & 0 \\
     1 & 0 & 0
    \end{pmatrix} $ -  not row echelon, leading entries are not in the column to the left to the leading entry below it\
    g. $\begin{pmatrix}
    1 & 2 & 3 \\
    1 & 0 & 0 \\
     0 & 1 & 1\\
     0 & 1 & 1
    \end{pmatrix} $ -  not row echelon, leading entry of the 2nd row is not to the right of the leading entry in the 1st row\
    h.$\begin{pmatrix}
    2 & 1 & 3 & 5\\
    0 & 0 & 1 & -1 \\
    0 & 0 & 0 & 3 \\
    0 & 0 & 0 & 0
    \end{pmatrix} $ - row echelon but not reduced, because leading entries are in the column to the left to the entry below it and row with all zeroes are at the bottom, but now reduced because leading entries are not 1

### 5. Solve the ff. systems of linear equations

a. $x_1 + 2x_2 - 3x_3 = 9$ \
    $ 2x_1 - x_2 -x_3 = 0 $ \
    $4x_1 - x_2 +x_3 = 4 $ \
    $\begin{bmatrix}
    1 & 2 & -3 & 9\\
    2 & -1 & -1 & 0\\
    4 & -1 & 1 & 4
    \end{bmatrix} 
    \xrightarrow[{R_3-4R_1}]{{R_2-2R_1}} 
    \begin{bmatrix}
    1 & 2 & -3 & 9\\
    0 & -5 & 5 & -18\\
    0 & -9 & 13 & -32
    \end{bmatrix} 
    \xrightarrow[]{{\frac{-1}{5}R_2}} 
    \begin{bmatrix}
    1 & 2 & -3 & 9\\
    0 & 1 & -1 & 18/5\\
    0 & -9 & 13 & -32
    \end{bmatrix} 
     \xrightarrow[]{{R_3+9R_2}} 
    \begin{bmatrix}
    1 & 2 & -3 & 9\\
    0 & 1 & -1 & 18/5\\
    0 & 0 & 4 & 2/5
    \end{bmatrix} 
     \xrightarrow[{\frac{1}{4}R_3}]{{R_1-2R_2}} 
    \begin{bmatrix}
    1 & 0 & -1 & 9/5\\
    0 & 1 & -1 & 18/5\\
    0 & 0 & 1 & 1/10
    \end{bmatrix} 
     \xrightarrow[{R_1+R_3}]{{R_2+R_3}} 
    \begin{bmatrix}
    1 & 0 & 0 & 19/10\\
    0 & 1 & 0 & 37/10\\
    0 & 0 & 1 & 1/10
    \end{bmatrix} 
    $\
    $x_1 = \frac{19}{10}$\
    $x_2 = \frac{37}{10}$\
    $x_3 = \frac{1}{10}$

In [127]:
A = np.array([[1.0, 2.0, -3.0, 9.0],
              [2.0, -1.0, -1.0, 0.0],
              [4.0, -1.0, 1.0, 4]], dtype=float)

A1 = RowAdd(A,0,1,-2)
A1 = RowAdd(A1,0,2,-4)
print("A1")
print(A1);

A2 = RowScale(A1,1,-1.0/5)
print("A2")
print(A2);

A3 = RowAdd(A2,1,2,9)
print("A3")
print(A3);

A4 = RowAdd(A3,1,0,-2)
A4= RowScale(A4,2,1.0/4)
print("A4")
print(A4);

A5 = BackwardSubstitution(A4)
print("A5")
print(A5);

A1
[[  1.   2.  -3.   9.]
 [  0.  -5.   5. -18.]
 [  0.  -9.  13. -32.]]
A2
[[  1.    2.   -3.    9. ]
 [ -0.    1.   -1.    3.6]
 [  0.   -9.   13.  -32. ]]
A3
[[ 1.   2.  -3.   9. ]
 [-0.   1.  -1.   3.6]
 [ 0.   0.   4.   0.4]]
A4
[[ 1.   0.  -1.   1.8]
 [-0.   1.  -1.   3.6]
 [ 0.   0.   1.   0.1]]
A5
[1.9 3.7 0.1]


b. $x + 2y = -1$ \
    $ 2x + y + z = 1 $ \
    $-x - y - z = -1 $ \
     $\begin{bmatrix}
    1 & 2 & 0 & -1\\
    2 & 1 & 1 & 1\\
    -1 & 1 & -1 & 1
    \end{bmatrix} 
    \xrightarrow[{R_3 + R_1}]{{R_2-2R_1}}
    \begin{bmatrix}
    1 & 2 & 0 & -1\\
    0 & -3 & 1 & 3\\
    0 & 3 & -1 & -2
    \end{bmatrix} 
    \xrightarrow[]{{R_3+R_2}}
     \begin{bmatrix}
    1 & 2 & 0 & -1\\
    0 & -3 & 1 & 3\\
    0 & 0 & 0 & 1
    \end{bmatrix} 
    \xrightarrow[]{}
    $
    infinite solutions

In [128]:
A = np.array([[1.0, 2.0, 0.0, -1.0],
              [2.0, 1.0, 1.0, 1.0],
              [-1.0, 1.0, -1.0, -1.0]], dtype=float)

A1 = RowAdd(A,0,1,-2)
A1 = RowAdd(A1,0,2,1)
print("A1")
print(A1);

A2 = RowAdd(A1,1,2,1)
print("A2")
print(A2);

A3 = BackwardSubstitution(A2)
print("A3")
print(A3);

A1
[[ 1.  2.  0. -1.]
 [ 0. -3.  1.  3.]
 [ 0.  3. -1. -2.]]
A2
[[ 1.  2.  0. -1.]
 [ 0. -3.  1.  3.]
 [ 0.  0.  0.  1.]]
A3
[nan inf inf]


/var/folders/gz/h6s5flr16sqcrdbrjz0xxdc40000gn/T/ipykernel_87948/2680572774.py:67: RuntimeWarning: divide by zero encountered in scalar divide
  x[i] = A[i, -1] / A[i, i]
/var/folders/gz/h6s5flr16sqcrdbrjz0xxdc40000gn/T/ipykernel_87948/2680572774.py:70: RuntimeWarning: invalid value encountered in scalar multiply
  A[j, -1] -= A[j, i] * x[i]


c. $x_1 -3x_2 - 2x_3 = 0$ \
    $ -x_1 + 2x_2 + x_3 = 0 $ \
    $2x_1 + 4x_2 + 6x_3 = 0 $ \
    $\begin{bmatrix}
    1 & -3 & -2 & 0\\
    -1 & 2 & 1 & 0\\
    2 & 4 & 6 & 0
    \end{bmatrix} 
    \xrightarrow[{R_3 - 2R_1}]{{R_2 + R_1}}
    \begin{bmatrix}
    1 & -3 & -2 & 0\\
    0 & -1 & -1 & 0\\
    0 & 10 & 10 & 0
    \end{bmatrix} 
    \xrightarrow[]{{\frac{1}{10}R_3}}
    \begin{bmatrix}
    1 & -3 & -2 & 0\\
    0 & -1 & -1 & 0\\
    0 & 1 & 1 & 0
    \end{bmatrix} 
    \xrightarrow[]{{R_3+R_2}}
    \begin{bmatrix}
    1 & -3 & -2 & 0\\
    0 & -1 & -1 & 0\\
    0 & 0 & 0 & 0
    \end{bmatrix} 
    \xrightarrow[]{{}}
    $
    unsolvable

In [129]:
A = np.array([[1.0, -3.0, -2.0, 0],
              [-1.0, 2.0, 1.0, 0.0],
              [2.0, 4.0, 6.0, 0.0]], dtype=float)

A1 = RowAdd(A,0,1,1)
A1 = RowAdd(A1,0,2,-2)
print("A1")
print(A1);

A2 = RowScale(A1,2,1.0/10)
print("A2")
print(A2);

A3 = RowAdd(A2,1,2,1)
print("A3")
print(A3);


A4 = BackwardSubstitution(A3)
print("A4")
print(A4);

A1
[[ 1. -3. -2.  0.]
 [ 0. -1. -1.  0.]
 [ 0. 10. 10.  0.]]
A2
[[ 1. -3. -2.  0.]
 [ 0. -1. -1.  0.]
 [ 0.  1.  1.  0.]]
A3
[[ 1. -3. -2.  0.]
 [ 0. -1. -1.  0.]
 [ 0.  0.  0.  0.]]
A4
[nan nan nan]


/var/folders/gz/h6s5flr16sqcrdbrjz0xxdc40000gn/T/ipykernel_87948/2680572774.py:67: RuntimeWarning: invalid value encountered in scalar divide
  x[i] = A[i, -1] / A[i, i]


d. $w + x + 2y + z = 1$ \
    $ w - x - y + z = 0 $ \
    $x + y = 1 $ \
    $ w + x + z = 2 $ \
    $\begin{bmatrix}
    1 & 1 & 2 & 1 & 1\\
    1 & -1 & -1 & 1 & 0\\
    0 & 1 & 1 & 0 & 1\\
    1 & 1 & 0 & 1 & 2
    \end{bmatrix} 
    \xrightarrow[{}]{{R_2 - R_1}}
     \begin{bmatrix}
    1 & 1 & 2 & 1 & 1\\
    0 & -2 & -3 & 0 & -1\\
    0 & 1 & 1 & 0 & 1\\
    1 & 1 & 0 & 1 & 2
    \end{bmatrix} 
    \xrightarrow[{}]{{R_3 + R_2}}
    \begin{bmatrix}
    1 & 1 & 2 & 1 & 1\\
    0 & -2 & -3 & 0 & -1\\
    0 & -1 & -2 & 0 & 0\\
    1 & 1 & 0 & 1 & 2
    \end{bmatrix} 
    \xrightarrow[{R_1-R_4}]{{R_3(-1)}}
    \begin{bmatrix}
    0 & 0 & 2 & 0 & -1\\
    0 & -2 & -3 & 0 & -1\\
    0 & 1 & 2 & 0 & 0\\
    1 & 1 & 0 & 1 & 2
    \end{bmatrix} 
    \xrightarrow[{}]{{\frac{-1}{2}R_2}}
    \begin{bmatrix}
    0 & 0 & 2 & 0 & -1\\
    0 & 1 & 3/2 & 0 & 1/2\\
    0 & 1 & 2 & 0 & 0\\
    1 & 1 & 0 & 1 & 2
    \end{bmatrix} 
    \xrightarrow[{}]{{R_3-R_2}}
    \begin{bmatrix}
    0 & 0 & 2 & 0 & -1\\
    0 & 1 & 3/2 & 0 & 1/2\\
    0 & 0 & 1/2 & 0 & -1/2\\
    1 & 1 & 0 & 1 & 2
    \end{bmatrix} 
    \xrightarrow[{}]{{R_1-4R_3}}
    \begin{bmatrix}
     0 & 0 & 0 & 0 & -1\\
    0 & 1 & 3/2 & 0 & 1/2\\
    0 & 0 & 1/2 & 0 & -1/2\\
    1 & 1 & 0 & 1 & 2
    \end{bmatrix} 
    \xrightarrow[{}]{{}}
    infinite \ solution
    $

In [130]:
A = np.array([[1.0, 1.0, 2.0, 1.0, 1.0],
              [1.0, -1.0, -1.0, 1.0,0.0],
              [0.0, 1.0, 1.0, 0.0,1.0],
              [1.0, 1.0, 0.0, 1.0,2.0]], dtype=float)

A1 = RowAdd(A,0,1,-1)
print("A1")
print(A1);

A2 = RowAdd(A1,1,2,1)
print("A2")
print(A2);

A3 = RowAdd(A2,3,0,-1)
A3 = RowScale(A3,2,-1)
print("A3")
print(A3);

A4 = RowScale(A3,1,-1.0/2.0)
print("A4")
print(A4);

A5 = RowAdd(A4,1,2,-1)
print("A5")
print(A5);

A6 = RowAdd(A5,2,0,-4)
print("A6")
print(A6);


A7 = BackwardSubstitution(A6)
print("A7")
print(A7);

A1
[[ 1.  1.  2.  1.  1.]
 [ 0. -2. -3.  0. -1.]
 [ 0.  1.  1.  0.  1.]
 [ 1.  1.  0.  1.  2.]]
A2
[[ 1.  1.  2.  1.  1.]
 [ 0. -2. -3.  0. -1.]
 [ 0. -1. -2.  0.  0.]
 [ 1.  1.  0.  1.  2.]]
A3
[[ 0.  0.  2.  0. -1.]
 [ 0. -2. -3.  0. -1.]
 [-0.  1.  2. -0. -0.]
 [ 1.  1.  0.  1.  2.]]
A4
[[ 0.   0.   2.   0.  -1. ]
 [-0.   1.   1.5 -0.   0.5]
 [-0.   1.   2.  -0.  -0. ]
 [ 1.   1.   0.   1.   2. ]]
A5
[[ 0.   0.   2.   0.  -1. ]
 [-0.   1.   1.5 -0.   0.5]
 [ 0.   0.   0.5  0.  -0.5]
 [ 1.   1.   0.   1.   2. ]]
A6
[[ 0.   0.   0.   0.   1. ]
 [-0.   1.   1.5 -0.   0.5]
 [ 0.   0.   0.5  0.  -0.5]
 [ 1.   1.   0.   1.   2. ]]
A7
[inf  2. -1.  2.]


/var/folders/gz/h6s5flr16sqcrdbrjz0xxdc40000gn/T/ipykernel_87948/2680572774.py:67: RuntimeWarning: divide by zero encountered in scalar divide
  x[i] = A[i, -1] / A[i, i]


### 6. Determine if the vectors are linear combinations

a. $ v= \begin{bmatrix}
    1 \\
    2 
    \end{bmatrix} 
    u_2= \begin{bmatrix}
    -1 \\
    3 
    \end{bmatrix} 
    u_3= \begin{bmatrix}
    2 \\
    -6 
    \end{bmatrix} 
    $ \
    $ \begin{bmatrix}
    -1 \\
    3 
    \end{bmatrix} x + 
    \begin{bmatrix}
    2 \\
    -6 
    \end{bmatrix} y = 
    \begin{bmatrix}
    1 \\
    2 
    \end{bmatrix} 
    $\
    $-x + 2y = 1$ \
    $ 3x - 6y = 2 $ \
    $
    \begin{bmatrix}
    -1 & 2 & 1 \\
    3 & -6 & 2
    \end{bmatrix}
    \xrightarrow[{}]{{R_2+3R_1}}
     \begin{bmatrix}
    -1 & 2 & 1 \\
    0 & 0 & 5
    \end{bmatrix}
     \xrightarrow[{}]{{}}
     infinite \ solutions
    $ \
    Therefore not linear combination

In [131]:
A = np.array([[-1.0, 2.0, 1.0],
              [3.0, -6.0, 2.0]], dtype=float)

A1 = RowAdd(A,0,1,3)
print("A1")
print(A1);

A2 = BackwardSubstitution(A1)
print("A2")
print(A2);

A1
[[-1.  2.  1.]
 [ 0.  0.  5.]]
A2
[inf inf]


/var/folders/gz/h6s5flr16sqcrdbrjz0xxdc40000gn/T/ipykernel_87948/2680572774.py:67: RuntimeWarning: divide by zero encountered in scalar divide
  x[i] = A[i, -1] / A[i, i]


b. $ v= \begin{bmatrix}
    1 \\
    2 \\
    3
    \end{bmatrix} 
    u_2= \begin{bmatrix}
    1 \\
    1 \\
    0
    \end{bmatrix} 
    u_3= \begin{bmatrix}
    0 \\
    1 \\
    1
    \end{bmatrix} 
    $ \
    $ \begin{bmatrix}
    1 \\
    1 \\
    0
    \end{bmatrix} x + 
    \begin{bmatrix}
    0 \\
    1 \\
    1
    \end{bmatrix} y = 
    \begin{bmatrix}
    1 \\
    2 \\
    3
    \end{bmatrix} 
    $\
    $x = 1$ \
    $ x + y = 2 $ \
    $ y = 3 $ \
    $
    \begin{bmatrix}
    1 & 0 & 1 \\
    1 & 1 & 2 \\
    0 & 1 & 3 \\
    \end{bmatrix}
    \xrightarrow[{}]{{R_2-R_1}}
     \begin{bmatrix}
     1 & 0 & 1 \\
     0 & 1 & 1 \\
     0 & 1 & 3 \\
    \end{bmatrix}
      \xrightarrow[{}]{{R_3-R_2}}
     \begin{bmatrix}
     1 & 0 & 1 \\
     0 & 1 & 1 \\
     0 & 0 & 2 \\
    \end{bmatrix}
    \xrightarrow[{}]{{}}
     infinite \ solutions
    $ \
    Therefore not linear combination

In [132]:
A = np.array([[1.0, 0.0, 1.0],
              [1.0, 1.0, 2.0],
              [0.0, 1.0, 3.0]], dtype=float)

A1 = RowAdd(A,0,1,-1)
print("A1")
print(A1);

A2 = RowAdd(A1,1,2,-1)
print("A2")
print(A2);

A3 = BackwardSubstitution(A2)
print("A3 - no z value")
print(A3);

A1
[[1. 0. 1.]
 [0. 1. 1.]
 [0. 1. 3.]]
A2
[[1. 0. 1.]
 [0. 1. 1.]
 [0. 0. 2.]]
A3 - no z value
[0. 0. 1.]


c. $ v= \begin{bmatrix}
    3 \\
    1 \\
    -2
    \end{bmatrix} 
    u_2= \begin{bmatrix}
    1 \\
    1 \\
    0
    \end{bmatrix} 
    u_3= \begin{bmatrix}
    0 \\
    1 \\
    1
    \end{bmatrix} 
    $ \
    $ \begin{bmatrix}
    1 \\
    1 \\
    0
    \end{bmatrix} x + 
    \begin{bmatrix}
    0 \\
    1 \\
    1
    \end{bmatrix} y = 
    \begin{bmatrix}
    3 \\
    1 \\
    -2
    \end{bmatrix} 
    $\
    $x = 3$ \
    $ x + y = 1 $ \
    $ y = -2 $ \
    $
    \begin{bmatrix}
    1 & 0 & 3 \\
    1 & 1 & 1 \\
    0 & 1 & -2 \\
    \end{bmatrix}
    \xrightarrow[{}]{{R_2-R_1}}
     \begin{bmatrix}
     1 & 0 & 3 \\
     0 & 1 & -2 \\
     0 & 1 & -2 \\
    \end{bmatrix}
      \xrightarrow[{}]{{R_3-R_2}}
     \begin{bmatrix}
     1 & 0 & 3 \\
     0 & 1 & -2\\
     0 & 0 & 0 \\
    \end{bmatrix}
    $ \
    $ x = 3$
    $ y = 2$ \
    Therefore linear combination

In [133]:
A = np.array([[1.0, 0.0, 3.0],
              [1.0, 1.0, 1.0],
              [0.0, 1.0, -2.0]], dtype=float)

A1 = RowAdd(A,0,1,-1)
print("A1")
print(A1);

A2 = RowAdd(A1,1,2,-1)
print("A2")
print(A2);

A3 = BackwardSubstitution(A2)
print("A3")
print(A3);

A1
[[ 1.  0.  3.]
 [ 0.  1. -2.]
 [ 0.  1. -2.]]
A2
[[ 1.  0.  3.]
 [ 0.  1. -2.]
 [ 0.  0.  0.]]
A3
[nan nan nan]


/var/folders/gz/h6s5flr16sqcrdbrjz0xxdc40000gn/T/ipykernel_87948/2680572774.py:67: RuntimeWarning: invalid value encountered in scalar divide
  x[i] = A[i, -1] / A[i, i]


### 7. Show that ff. vectors are a span

a. $span(\begin{bmatrix}
    1 \\
    1 \\
    \end{bmatrix} 
    \begin{bmatrix}
    1 \\
    -1 \\
    \end{bmatrix}) 
    \xrightarrow[{}]{{}}
    \begin{bmatrix}
    1 & 1& a\\
    1 & -1& b\\
    \end{bmatrix} 
     \xrightarrow[{}]{{R_2-R_1}}
    \begin{bmatrix}
    1 & 1& a\\
    0 & -2& b-a\\
    \end{bmatrix} 
     \xrightarrow[{}]{{\frac{-1}{2}R_2}}
    \begin{bmatrix}
    1 & 1& a\\
    0 & 1& \frac{-b+a}{2}\\
    \end{bmatrix} 
     \xrightarrow[{}]{{R_1-R_2}}
    \begin{bmatrix}
    1 & 0& a - \frac{-b+a}{2}\\
    0 & 1& \frac{-b+a}{2}\\
    \end{bmatrix} 
    $ \
    Therefore vectors are a span

b.  $span(\begin{bmatrix}
    1 \\
    0 \\
    1
    \end{bmatrix} 
    \begin{bmatrix}
    1 \\
    1 \\
    0
    \end{bmatrix}) 
     \begin{bmatrix}
    0 \\
    1 \\
    1
    \end{bmatrix}) 
    \xrightarrow[{}]{{}}
    \begin{bmatrix}
    1 & 1 & 0 & a \\
    0 & 1 & 1 & b \\
    1 & 0 & 1 & c \\
    \end{bmatrix}) 
    \xrightarrow[{}]{{R_3-R_1}}
    \begin{bmatrix}
    1 & 1 & 0 & a \\
    0 & 1 & 1 & b \\
    0 & -1 & 1 & c-a \\
    \end{bmatrix}) 
    \xrightarrow[{}]{{R_3+R_2}}
     \begin{bmatrix}
    1 & 1 & 0 & a \\
    0 & 1 & 1 & b \\
    0 & 0 & 2 & c-a+b \\
    \end{bmatrix}) 
    \xrightarrow[{}]{{\frac{1}{2}R_3}}
     \begin{bmatrix}
    1 & 1 & 0 & a \\
    0 & 1 & 1 & b \\
    0 & 0 & 1 & \frac{c-a+b}{2} \\
    \end{bmatrix}) 
    \xrightarrow[{}]{{R_2-R_3}}
     \begin{bmatrix}
    1 & 1 & 0 & a \\
    0 & 1 & 0 & b - \frac{c-a+b}{2}\\
    0 & 0 & 1 & \frac{c-a+b}{2} \\
    \end{bmatrix}) 
    \xrightarrow[{}]{{R_1-R_2}}
    \begin{bmatrix}
    1 & 0 & 0 & a - b - \frac{c-a+b}{2} \\
    0 & 1 & 0 & b - \frac{c-a+b}{2}\\
    0 & 0 & 1 & \frac{c-a+b}{2} \\
    \end{bmatrix}) 
    $ \
    Therefore vector is a span
    
c. C has the same given with b

### 8. Show that the ff. vectors are linearly independent

a.  $
    \begin{bmatrix} 3 \\ -1 \\ 1 \\ -1 \end{bmatrix}
    \begin{bmatrix} -1 \\ 2 \\ 1 \\ -1 \end{bmatrix}
    \begin{bmatrix} 1 \\ 1 \\ 3 \\ 1 \end{bmatrix}
    \begin{bmatrix} -1 \\ -1 \\ 1 \\ 3 \end{bmatrix}
    \xrightarrow[{}]{{}}
    \begin{bmatrix} 
    3 & -1 & 1 & -1 & 0\\
    -1 & 2 & 1 & -1 &0\\
    1 & 1 & 3 & 1 & 0\\
    -1 & -1 & 1 & 3 & 0
    \end{bmatrix}
    \xrightarrow[{}]{{\frac{1}{3}R_1}}
    \begin{bmatrix} 
    1 & -1/3 & 1/3 & -1/3 & 0\\
    -1 & 2 & 1 & -1 &0\\
    1 & 1 & 3 & 1 & 0\\
    -1 & -1 & 1 & 3 & 0
    \end{bmatrix}
    \xrightarrow[{R_4+R_1}]{{R_2+R_1 \ \ ,R_3-R_1}}
    \begin{bmatrix} 
    1 & -1/3 & 1/3 & -1/3 & 0\\
    0 & 5/3 & 4/3 & -4/3 &0\\
    0 & 4/3 & 8/3 & 4/3 & 0\\
    0 & -4/3 & 4/3 & 8/3 & 0
    \end{bmatrix}
    \xrightarrow[{}]{{\frac{3}{5}R_2}}
    \begin{bmatrix} 
    1 & -1/3 & 1/3 & -1/3 & 0\\
    0 & 1 & 4/5 & -4/5 &0\\
    0 & 4/3 & 8/3 & 4/3 & 0\\
    0 & -4/3 & 4/3 & 8/3 & 0
    \end{bmatrix}
     \xrightarrow[{\frac{3}{4}R_4}]{{R_1+\frac{1}{3}R_2 \ \ R_3 - \frac{4}{3}R_2}}
    \begin{bmatrix} 
    1 & 0 & 3/5 & -3/5 & 0\\
    0 & 1 & 4/5 & -4/5 &0\\
    0 & 0 & 8/5 & 12/5 & 0\\
    0 & -1 & 1 & 2 & 0
    \end{bmatrix}
    $
    $
      \xrightarrow[{\frac{5}{8}R_3}]{{R_4+R_2}}
    \begin{bmatrix} 
    1 & 0 & 3/5 & -3/5 & 0\\
    0 & 1 & 4/5 & -4/5 &0\\
    0 & 0 & 1 & 3/2 & 0\\
    0 & 0 & 9/5 & 6/5 & 0
    \end{bmatrix}
    \xrightarrow[{R4 - \frac{9}{5}R_3}]{{R_1-\frac{3}{5}R_3 \ \ R_2 - \frac{4}{5}R_3}}
    \begin{bmatrix} 
    1 & 0 & 0 & -3/2 & 0\\
    0 & 1 & 0 & -2 &0\\
    0 & 0 & 1 & 3/2 & 0\\
    0 & 0 & 0 & -3/2 & 0
    \end{bmatrix}
    \xrightarrow[]{{\frac{-2}{3}R_4}}
    \begin{bmatrix} 
    1 & 0 & 0 & -3/2 & 0\\
    0 & 1 & 0 & -2 &0\\
    0 & 0 & 1 & 3/2 & 0\\
    0 & 0 & 0 & 1 & 0
    \end{bmatrix}
     \xrightarrow[{R3 - \frac{3}{2}R_4}]{{R_1-\frac{3}{2}R_4 \ \ R_2 + 2R_4}}
    \begin{bmatrix} 
    1 & 0 & 0 & 0 & 0\\
    0 & 1 & 0 & 0 &0\\
    0 & 0 & 1 & 0 & 0\\
    0 & 0 & 0 & 1 & 0
    \end{bmatrix}
    $ \
    It is RREF, therefore linearly independent

In [134]:
A = np.array([[3.0, -1.0, 1.0, -1.0, 0.0],
              [-1.0, 2.0, 1.0, -1.0, 0.0],
              [1.0, 1.0, 3.0, 1.0, 0.0],
              [-1.0, -1.0, 1.0, 3.0, 0.0]], dtype=float)

np.set_printoptions(precision=2, suppress=True)

A1 = RowScale(A,0,1.0/3.0)
print("A1")
print(A1);

A2 = RowAdd(A1,0,1,1)
A2 = RowAdd(A2,0,2,-1)
A2 = RowAdd(A2,0,3,1)
print("A2")
print(A2);

A3 = RowScale(A2,1,3.0/5.0)
print("A3")
print(A3);

A4 = RowAdd(A3,1,0,1.0/3.0)
A4 = RowAdd(A4,1,2,-4.0/3.0)
A4= RowScale(A4,3,3.0/4.0)
print("A4")
print(A4);

A5 = RowAdd(A4,1,3,1)
A5= RowScale(A5,2,5.0/8.0)
print("A5")
print(A5);

A6 = RowAdd(A5,2,0,-3.0/5.0)
A6 = RowAdd(A6,2,1,-4.0/5.0)
A6 = RowAdd(A6,2,3,-9.0/5.0)
print("A6")
print(A6);

A7= RowScale(A6,3,-2.0/3.0)
print("A7")
print(A7);

A8 = BackwardSubstitution(A7)
print("A8 - Therefore Linearly Independent")
print(A8);

A1
[[ 1.   -0.33  0.33 -0.33  0.  ]
 [-1.    2.    1.   -1.    0.  ]
 [ 1.    1.    3.    1.    0.  ]
 [-1.   -1.    1.    3.    0.  ]]
A2
[[ 1.   -0.33  0.33 -0.33  0.  ]
 [ 0.    1.67  1.33 -1.33  0.  ]
 [ 0.    1.33  2.67  1.33  0.  ]
 [ 0.   -1.33  1.33  2.67  0.  ]]
A3
[[ 1.   -0.33  0.33 -0.33  0.  ]
 [ 0.    1.    0.8  -0.8   0.  ]
 [ 0.    1.33  2.67  1.33  0.  ]
 [ 0.   -1.33  1.33  2.67  0.  ]]
A4
[[ 1.   0.   0.6 -0.6  0. ]
 [ 0.   1.   0.8 -0.8  0. ]
 [ 0.   0.   1.6  2.4  0. ]
 [ 0.  -1.   1.   2.   0. ]]
A5
[[ 1.   0.   0.6 -0.6  0. ]
 [ 0.   1.   0.8 -0.8  0. ]
 [ 0.   0.   1.   1.5  0. ]
 [ 0.   0.   1.8  1.2  0. ]]
A6
[[ 1.   0.  -0.  -1.5  0. ]
 [ 0.   1.  -0.  -2.   0. ]
 [ 0.   0.   1.   1.5  0. ]
 [ 0.   0.  -0.  -1.5  0. ]]
A7
[[ 1.   0.  -0.  -1.5  0. ]
 [ 0.   1.  -0.  -2.   0. ]
 [ 0.   0.   1.   1.5  0. ]
 [-0.  -0.   0.   1.  -0. ]]
A8 - Therefore Linearly Independent
[ 0.  0.  0. -0.]


b.  $
    \begin{bmatrix} 0 \\ 0\\ 0 \\ 4 \end{bmatrix}
    \begin{bmatrix} 0 \\ 0 \\ 3 \\ 3 \end{bmatrix}
    \begin{bmatrix} 0 \\ 2 \\ 2 \\ 2 \end{bmatrix}
    \begin{bmatrix} 1 \\ 1 \\ 1 \\ 1 \end{bmatrix}
    \xrightarrow[{}]{{}}
    \begin{bmatrix} 
    0 & 0 & 0 & 4 \\
    0 & 0 & 3 & 3 \\
    0 & 2 & 2 & 1 \\
    1 & 1 & 1 & 1 
    \end{bmatrix}
    \xrightarrow[{R_2 <=> R_3}]{{R_1 <=> R_4}}
    \begin{bmatrix} 
    1 & 1 & 1 & 1 \\
    0 & 2 & 2 & 2 \\
    0 & 0 & 3 & 2 \\
    0 & 0 & 0 & 4 
    \end{bmatrix}
    \xrightarrow[{\frac{1}{4}R_4}]{{\frac{1}{2}R_1 \ \ \frac{1}{3}R_3}}
    \begin{bmatrix} 
    1 & 1 & 1 & 1 \\
    0 & 1 & 1 & 1 \\
    0 & 0 & 1 & 1\\
    0 & 0 & 0 & 1 
    \end{bmatrix}
    $ \
    $ Rank(A) < m $ \
    $ 6 \nless 4 $ \
    Therefore, linearly independent

c.  $
    \begin{bmatrix} 1 \\ -1\\ 1 \\ 0 \end{bmatrix}
    \begin{bmatrix} -1 \\ 1 \\ 0 \\ 1 \end{bmatrix}
    \begin{bmatrix} 1 \\ 0 \\ 1 \\ -1 \end{bmatrix}
    \begin{bmatrix} 0 \\ 1 \\ -1 \\ 1 \end{bmatrix}
    \xrightarrow[{}]{{}}
    \begin{bmatrix} 
    1 & -1 & 1 & 0 \\
    -1 & 1 & 0 & 1 \\
    1 & 0 & 1 & -1 \\
    0 & 1 & -1 & 1 
    \end{bmatrix}
    \xrightarrow[{}]{{R_2 <=> R_4}}
    \begin{bmatrix} 
    1 & -1 & 1 & 0 \\
    0 & 1 & -1 & 1 \\
    1 & 0 & 1 & -1 \\
    -1 & 1 & 0 & 1 
    \end{bmatrix}
    \xrightarrow[{}]{{R_4+R_1}}
    \begin{bmatrix} 
    1 & -1 & 1 & 0 \\
    0 & 1 & -1 & 1 \\
    1 & 0 & 1 & -1 \\
    0 & 0 & 1 & 1 
    \end{bmatrix}
    $
    $
    \xrightarrow[{}]{{R_4 <=> R_3}}
    \begin{bmatrix} 
    1 & -1 & 1 & 0 \\
    0 & 1 & -1 & 1 \\
    0 & 0 & 1 & 1 \\
    1 & 0 & 1 & -1 
    \end{bmatrix}
    \xrightarrow[{}]{{R_4 - R_1}}
    \begin{bmatrix} 
    1 & -1 & 1 & 0 \\
    0 & 1 & -1 & 1 \\
    0 & 0 & 1 & 1 \\
    0 & 1 & 0 & -1 
    \end{bmatrix}
    \xrightarrow[{R_1+R_2}]{{R_4 - R_2}}
    \begin{bmatrix} 
    1 & 0 & 0 & 1 \\
    0 & 1 & -1 & 1 \\
    0 & 0 & 1 & 1 \\
    0 & 0 & 1 & -2 
    \end{bmatrix}
    \xrightarrow[{R_2+R_3}]{{R_4 - R_3}}
    \begin{bmatrix} 
    1 & 0 & 0 & 1 \\
    0 & 1 & 0 & 2 \\
    0 & 0 & 1 & 1 \\
    0 & 0 & 0 & -3 
    \end{bmatrix}
    \xrightarrow[{}]{{\frac{-1}{3}R_4}}
    \begin{bmatrix} 
    1 & 0 & 0 & 1 \\
    0 & 1 & 0 & 2 \\
    0 & 0 & 1 & 1 \\
    0 & 0 & 0 & 1 
    \end{bmatrix}
    \xrightarrow[{R_3 - R_4}]{{R_1-R_4 \ \ R_2 - 2R4}}
    \begin{bmatrix} 
    1 & 0 & 0 & 0 \\
    0 & 1 & 0 & 0 \\
    0 & 0 & 1 & 0 \\
    0 & 0 & 0 & 1 
    \end{bmatrix}
    $ \
    This is an RREF, therefore linearly independent

In [135]:
A = np.array([[1.0, -1.0, 1.0, 0.0],
              [-1.0, 1.0, 0.0, 1.0],
              [1.0, 0.0, 1.0, -1.0],
              [0.0, 1.0, -1.0, 1.0]], dtype=float)

A1 = RowSwap(A,1,3)
print("A1")
print(A1);

A2 = RowAdd(A1,0,3,1)
print("A2")
print(A2);

A3 = RowSwap(A2,3,2)
print("A3")
print(A3);

A4 = RowAdd(A3,0,3,-1)
print("A4")
print(A4);

A5 = RowAdd(A4,1,3,-1)
A5 = RowAdd(A5,1,0,1)
print("A5")
print(A5);

A6 = RowAdd(A5,2,3,-1)
A6 = RowAdd(A6,2,1,1)
print("A6")
print(A6);

A7= RowScale(A6,3,-1.0/3.0)
print("A7")
print(A7);

A8 = RowAdd(A7,3,0,-1)
A8 = RowAdd(A8,3,1,-2)
A8 = RowAdd(A8,3,2,-1)
print("A8 - Therefore, Linearly Independent")
print(A8);

A1
[[ 1. -1.  1.  0.]
 [ 0.  1. -1.  1.]
 [ 1.  0.  1. -1.]
 [-1.  1.  0.  1.]]
A2
[[ 1. -1.  1.  0.]
 [ 0.  1. -1.  1.]
 [ 1.  0.  1. -1.]
 [ 0.  0.  1.  1.]]
A3
[[ 1. -1.  1.  0.]
 [ 0.  1. -1.  1.]
 [ 0.  0.  1.  1.]
 [ 1.  0.  1. -1.]]
A4
[[ 1. -1.  1.  0.]
 [ 0.  1. -1.  1.]
 [ 0.  0.  1.  1.]
 [ 0.  1.  0. -1.]]
A5
[[ 1.  0.  0.  1.]
 [ 0.  1. -1.  1.]
 [ 0.  0.  1.  1.]
 [ 0.  0.  1. -2.]]
A6
[[ 1.  0.  0.  1.]
 [ 0.  1.  0.  2.]
 [ 0.  0.  1.  1.]
 [ 0.  0.  0. -3.]]
A7
[[ 1.  0.  0.  1.]
 [ 0.  1.  0.  2.]
 [ 0.  0.  1.  1.]
 [-0. -0. -0.  1.]]
A8 - Therefore, Linearly Independent
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [-0. -0. -0.  1.]]
